using System.Diagnostics;
using System.Xml.Linq;

namespace Faro.Editor;

/// <summary>
/// Android APK of a C# project (File › Build Android APK, or `Faro.Editor --build-apk &lt;folder&gt;`). A head project generated
/// in .faro/android compiles Source/ with Avalonia.Android and packs faro.json, UI/, Bindings/ and Assets/ into the APK; its
/// MainActivity unpacks them and starts the runtime binder. Needs the .NET "android" workload; the Android SDK and a JDK are
/// installed on first use (ANDROID_HOME / JAVA_HOME are used when set). The APK is signed with the debug key (installable
/// for testing; the Play Store needs your own key).
/// </summary>
public static class AndroidApk
{
    const string Framework = "net10.0-android";

    public static string Head(string root) => Path.Combine(root, ".faro", "android");

    /// <summary>"Hello Faro!" → "io.faro.hellofaro": lower-case letters and digits, starting with a letter.</summary>
    public static string ApplicationId(string name)
    {
        var id = new string([.. name.ToLowerInvariant().Where(char.IsAsciiLetterOrDigit)]).TrimStart("0123456789".ToCharArray());
        return "io.faro." + (id.Length > 0 ? id : "app");
    }

    /// <summary>Writes the head project; its references are the project's own (Faro.Runtime and any others), paths re-rooted.</summary>
    public static string Write(string root)
    {
        var name = Name(root);
        var head = Head(root);
        Directory.CreateDirectory(head);
        var references = Directory.EnumerateFiles(root, "*.csproj").SelectMany(p =>
            XDocument.Load(p).Descendants().Where(e => e.Name.LocalName is "PackageReference" or "ProjectReference").Select(e =>
            {
                var copy = new XElement(e.Name.LocalName, e.Attributes());
                if (e.Name.LocalName == "ProjectReference") copy.SetAttributeValue("Include", Path.GetRelativePath(head, Path.Combine(root, (string)e.Attribute("Include")!)));
                return copy;
            }));
        var assets = new[] { "UI", "Bindings", "Assets" }.Select(d => new XElement("AndroidAsset",
            new XAttribute("Include", $"../../{d}/**"), new XAttribute("Link", $"faro/{d}/%(RecursiveDir)%(Filename)%(Extension)")));
        var csproj = new XDocument(new XElement("Project", new XAttribute("Sdk", "Microsoft.NET.Sdk"),
            new XComment(" Generated by Faro for File › Build Android APK; rewritten on every build. "),
            new XElement("PropertyGroup",
                new XElement("TargetFramework", Framework),
                new XElement("SupportedOSPlatformVersion", "24"),
                new XElement("OutputType", "Exe"),
                new XElement("Nullable", "enable"),
                new XElement("ImplicitUsings", "enable"),
                new XElement("AssemblyName", name),
                new XElement("ApplicationId", ApplicationId(name)),
                new XElement("ApplicationTitle", name),
                new XElement("AndroidPackageFormat", "apk"),
                new XElement("TrimMode", "partial"), // user classes are found by reflection (bindings)
                new XElement("EnableDefaultCompileItems", "false")),
            new XElement("ItemGroup",
                new XElement("Compile", new XAttribute("Include", "MainActivity.cs")),
                new XElement("Compile", new XAttribute("Include", "../../Source/**/*.cs")),
                new XElement("AndroidAsset", new XAttribute("Include", "../../faro.json"), new XAttribute("Link", "faro/faro.json")),
                assets,
                new XElement("PackageReference", new XAttribute("Include", "Avalonia.Android"), new XAttribute("Version", AvaloniaVersion)),
                references)));
        var path = Path.Combine(head, name + ".Android.csproj");
        csproj.Save(path);
        File.WriteAllText(Path.Combine(head, "MainActivity.cs"), $$"""
            // Generated by Faro: unpacks the project (faro.json, UI, Bindings, Assets) from the APK and starts the runtime binder.
            using Android.App;
            using Android.Content.PM;
            using Android.Runtime;
            using Avalonia.Android;

            namespace FaroAndroid;

            [Application]
            public class FaroAndroidApp(IntPtr handle, JniHandleOwnership ownership) : AvaloniaAndroidApplication<Faro.Runtime.FaroApplication>(handle, ownership)
            {
                public override void OnCreate()
                {
                    var root = Path.Combine(FilesDir!.AbsolutePath, "faro");
                    Unpack("faro", root);
                    Faro.Runtime.FaroApp.Init(typeof(FaroAndroidApp).Assembly, root);
                    base.OnCreate();
                }

                void Unpack(string asset, string target)
                {
                    var children = Assets!.List(asset)!;
                    if (children.Length == 0)
                    {
                        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
                        using var from = Assets.Open(asset);
                        using var to = File.Create(target);
                        from.CopyTo(to);
                        return;
                    }
                    foreach (var child in children) Unpack($"{asset}/{child}", Path.Combine(target, child));
                }
            }

            [Activity(Label = "{{name}}", MainLauncher = true, Theme = "@style/Theme.AppCompat.NoActionBar",
                ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.UiMode)]
            public class MainActivity : AvaloniaMainActivity;

            """);
        return path;
    }

    /// <summary>The app's name: its .csproj's (the desktop assembly), else the folder's.</summary>
    static string Name(string root) => Directory.EnumerateFiles(root, "*.csproj").Select(Path.GetFileNameWithoutExtension).FirstOrDefault() ?? Path.GetFileName(root);

    /// <summary>The Avalonia version Faro (and so Faro.Runtime) is built with: Avalonia.Android must match it.</summary>
    static string AvaloniaVersion => typeof(Avalonia.Application).Assembly.GetName().Version!.ToString(3);

    /// <summary>Installs the Android SDK / JDK if missing, publishes, and copies the APK to dist/&lt;name&gt;.apk (returned; null on failure).</summary>
    public static async Task<string?> BuildAsync(string root, Action<string> output, CancellationToken cancel = default)
    {
        var csproj = Write(root);
        var tools = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Faro", "android");
        var sdk = Environment.GetEnvironmentVariable("ANDROID_HOME") ?? Environment.GetEnvironmentVariable("ANDROID_SDK_ROOT") ?? Path.Combine(tools, "sdk");
        string[] properties = [$"-p:AndroidSdkDirectory={sdk}", "-p:AcceptAndroidSDKLicenses=True",
            .. Environment.GetEnvironmentVariable("JAVA_HOME") is null ? [$"-p:JavaSdkDirectory={Path.Combine(tools, "jdk")}"] : Array.Empty<string>()];
        var published = Path.Combine(Head(root), "out");
        if (Directory.Exists(published)) Directory.Delete(published, true);
        output(L.T("Installing the Android SDK and JDK if needed (the first build downloads them)…"));
        if (await Exec(["build", csproj, "-t:InstallAndroidDependencies", "-f", Framework, .. properties], output, cancel) != 0) return null;
        if (await Exec(["publish", csproj, "-c", "Release", "-f", Framework, "-o", published, .. properties], output, cancel) != 0) return null;
        if (Directory.EnumerateFiles(published, "*-Signed.apk").FirstOrDefault() is not { } apk) return null;
        var target = Path.Combine(root, "dist", Name(root) + ".apk");
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.Copy(apk, target, true);
        return target;
    }

    static async Task<int> Exec(string[] args, Action<string> output, CancellationToken cancel)
    {
        using var process = new Process { StartInfo = new("dotnet", args) { RedirectStandardOutput = true, RedirectStandardError = true } };
        process.OutputDataReceived += (_, e) => { if (e.Data is { } line) output(line); };
        process.ErrorDataReceived += (_, e) => { if (e.Data is { } line) output(line); };
        try { process.Start(); }
        catch (System.ComponentModel.Win32Exception e) // the .NET SDK isn't installed
        {
            output(L.F("Couldn't start {0}: {1}", "dotnet", e.Message));
            return -1;
        }
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        using var stop = cancel.Register(() => process.Kill(entireProcessTree: true));
        await process.WaitForExitAsync(CancellationToken.None);
        return process.ExitCode;
    }
}
