using System.Text.Json;
using System.Text.Json.Nodes;

namespace Faro.Editor;

/// <summary>
/// Creating and initializing Faro projects (welcome screen). A Faro project is a folder with faro.json
/// (name and language: fixed at creation, spec §2), the four folders (spec §4), a .csproj, and the
/// Faro.Runtime package vendored in .faro/packages so the project builds wherever the folder goes.
/// </summary>
public static partial class ProjectSetup
{
    public const string ProjectFile = "faro.json";
    public static readonly string[] Templates = ["Empty", "Sample"];

    /// <summary>Documents/Faro, where new projects go by default.</summary>
    // MyDocuments is empty on Linux without an XDG documents folder; fall back to ~/Documents.
    public static string DefaultLocation => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) is { Length: > 0 } documents
            ? documents
            : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Documents"),
        "Faro");

    /// <summary>The editor ships the runtime package and the templates next to itself.</summary>
    static string AppDir => AppContext.BaseDirectory;

    public static bool IsFaroProject(string dir) => File.Exists(Path.Combine(dir, ProjectFile));

    [System.Text.RegularExpressions.GeneratedRegex(@"^[A-Za-z_][A-Za-z0-9_]*$")]
    private static partial System.Text.RegularExpressions.Regex NamePattern();

    /// <summary>Creates &lt;location&gt;/&lt;name&gt; from a template and returns its path.</summary>
    public static string Create(string location, string name, string template, string? appDir = null)
    {
        if (!NamePattern().IsMatch(name)) throw new ArgumentException($"'{name}' can't be a project name: use letters, digits and '_', starting with a letter.");
        if (!Path.IsPathRooted(location)) throw new ArgumentException("Choose a full folder path for the location.");
        var dir = Path.Combine(location, name);
        if (Directory.Exists(dir) && Directory.EnumerateFileSystemEntries(dir).Any()) throw new ArgumentException($"{dir} already exists and isn't empty.");
        Directory.CreateDirectory(dir);
        var startScreen = "MainScreen";
        if (template == "Sample")
            foreach (var file in Directory.EnumerateFiles(Path.Combine(appDir ?? AppDir, "templates", "Sample"), "*", SearchOption.AllDirectories))
            {
                var target = Path.Combine(dir, Path.GetRelativePath(Path.Combine(appDir ?? AppDir, "templates", "Sample"), file));
                Directory.CreateDirectory(Path.GetDirectoryName(target)!);
                File.Copy(file, target);
            }
        else
            foreach (var (path, text) in ProjectFiles.NewScreen(Faro.Runtime.FaroProject.Load(dir), startScreen))
                WriteNew(path, text!);
        Initialize(dir, name, startScreen, appDir);
        return dir;
    }

    /// <summary>
    /// Makes a folder a Faro project: adds only what is missing and never overwrites existing files.
    /// A folder that already has a .csproj keeps it (it then needs a Faro.Runtime reference of its own).
    /// </summary>
    public static void Initialize(string dir, string? name = null, string startScreen = "MainScreen", string? appDir = null)
    {
        name ??= new string(Path.GetFileName(Path.GetFullPath(dir).TrimEnd(Path.DirectorySeparatorChar)).Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray()) is { Length: > 0 } n && !char.IsDigit(n[0]) ? n : "FaroApp";
        foreach (var folder in new[] { "UI", "Source", "Bindings", "Assets" }) Directory.CreateDirectory(Path.Combine(dir, folder));

        var (package, version) = BundledRuntime(appDir);
        Vendor(dir, package);

        WriteNew(Path.Combine(dir, ProjectFile), new JsonObject { ["name"] = name, ["language"] = "CSharp", ["runtime"] = version.ToString(), ["startScreen"] = startScreen }.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n");
        WriteNew(Path.Combine(dir, "nuget.config"), """
            <?xml version="1.0" encoding="utf-8"?>
            <configuration>
              <packageSources>
                <add key="faro" value=".faro/packages" />
              </packageSources>
            </configuration>

            """);
        if (!Directory.EnumerateFiles(dir, "*.csproj").Any())
            WriteNew(Path.Combine(dir, name + ".csproj"), $"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <!-- Generated by Faro. Language: C# (fixed for this project). -->
                  <PropertyGroup>
                    <OutputType>WinExe</OutputType>
                    <TargetFramework>net10.0</TargetFramework>
                    <Nullable>enable</Nullable>
                    <ImplicitUsings>enable</ImplicitUsings>
                  </PropertyGroup>
                  <ItemGroup>
                    <PackageReference Include="Faro.Runtime" Version="{version}" />
                    <Content Include="faro.json;UI/**;Bindings/**;Assets/**" CopyToOutputDirectory="PreserveNewest" />
                    <!-- dotnet watch restarts the app when the UI graph or bindings change (spec §9). -->
                    <Watch Include="UI/**;Bindings/**" />
                  </ItemGroup>
                </Project>

                """);
        WriteNew(Path.Combine(dir, "Program.cs"), "Faro.Runtime.FaroApp.Run(args, typeof(Program).Assembly); // start screen: faro.json\n");
        WriteNew(Path.Combine(dir, ".gitignore"), "bin/\nobj/\n");
    }

    /// <summary>The newest Faro.Runtime package shipped with the editor (compared as versions, so 0.1.10 &gt; 0.1.9).</summary>
    public static (string Package, Version Version) BundledRuntime(string? appDir = null)
    {
        var packages = Path.Combine(appDir ?? AppDir, "runtime");
        return Directory.EnumerateFiles(packages, "Faro.Runtime.*.nupkg")
            .Select(p => (Package: p, Version: Version.TryParse(Path.GetFileNameWithoutExtension(p)["Faro.Runtime.".Length..], out var v) ? v : null))
            .Where(p => p.Version is not null).OrderBy(p => p.Version).Select(p => (p.Package, p.Version!)).LastOrDefault() is { Package: not null } latest
            ? latest
            : throw new InvalidOperationException($"The Faro.Runtime package is missing from {packages}.");
    }

    [System.Text.RegularExpressions.GeneratedRegex(@"(<PackageReference\s+Include=""Faro\.Runtime""\s+Version="")([^""]+)("")")]
    private static partial System.Text.RegularExpressions.Regex RuntimeReference();

    /// <summary>The Faro.Runtime version the project's .csproj references; null if it doesn't use the package (e.g. the in-repo sample).</summary>
    public static Version? ProjectRuntime(string dir) =>
        Directory.EnumerateFiles(dir, "*.csproj").Select(f => RuntimeReference().Match(File.ReadAllText(f)))
            .FirstOrDefault(m => m.Success) is { } m && Version.TryParse(m.Groups[2].Value, out var v) ? v : null;

    /// <summary>Runtime update check on open: the editor ships a newer runtime than the project uses.</summary>
    public static bool RuntimeUpdateAvailable(string dir, string? appDir = null) =>
        ProjectRuntime(dir) is { } used && used < BundledRuntime(appDir).Version;

    /// <summary>Moves the project to the bundled runtime: vendors the package, bumps the .csproj reference and faro.json.</summary>
    public static void UpdateRuntime(string dir, string? appDir = null)
    {
        var (package, version) = BundledRuntime(appDir);
        foreach (var old in Directory.EnumerateFiles(Path.Combine(dir, ".faro", "packages"), "Faro.Runtime.*.nupkg").Where(p => p != Path.Combine(dir, ".faro", "packages", Path.GetFileName(package))))
            File.Delete(old);
        Vendor(dir, package);
        foreach (var csproj in Directory.EnumerateFiles(dir, "*.csproj"))
            File.WriteAllText(csproj, RuntimeReference().Replace(File.ReadAllText(csproj), $"${{1}}{version}${{3}}"));
        var json = Path.Combine(dir, ProjectFile);
        if (File.Exists(json) && JsonNode.Parse(File.ReadAllText(json)) is JsonObject meta)
        {
            meta["runtime"] = version.ToString();
            File.WriteAllText(json, meta.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n");
        }
    }

    static void Vendor(string dir, string package)
    {
        var vendored = Path.Combine(dir, ".faro", "packages", Path.GetFileName(package));
        Directory.CreateDirectory(Path.GetDirectoryName(vendored)!);
        if (!File.Exists(vendored)) File.Copy(package, vendored);
    }

    static void WriteNew(string path, string text)
    {
        if (File.Exists(path)) return;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text);
    }

    /// <summary>Most recent first, without duplicates, at most 10 (kept in the app settings).</summary>
    public static void Remember(string dir)
    {
        var settings = FaroSettings.Current;
        settings.RecentProjects = [.. new[] { Path.GetFullPath(dir) }.Concat(settings.RecentProjects).Distinct().Take(10)];
        settings.Save();
    }
}
